# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Skyper's Blog
description: > # this means to ignore newlines until "baseurl:"
  Blog d'un passionné d'informatique, d'électronique, de sciences …
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.skyplabs.net" # the base hostname & protocol for your site

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Handling Reading
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor
  - scripts
  - .travis.yml

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: "<!--more-->"

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Outputting
permalink: :year/:month/:day/:title/
timezone: Europe/Paris

# Pagination
paginate: 5
paginate_path: "/page:num"
