# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Skyper's Blog
email: skyper@skyplabs.net
description: > # this means to ignore newlines until "baseurl:"
  Blog d'un passionné d'informatique, d'électronique, de sciences …
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.skyplabs.net" # the base hostname & protocol for your site
twitter_username: SkypLabs
github_username: SkypLabs

# Plugins
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
highlighter: rouge

# Serving
detach: true
port: 4000
host: 127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink: :year/:month/:day/:title/
timezone: Europe/Paris

# Pagination
paginate: 5
paginate_path: "/page:num"

kramdown:
  input: GFM
